#!/bin/sh

patch_file=".git/patches/master/patch"
override=false
orig_git=$(which git)

check()
{
	cat > "$patch_file"
	touch_date 1727032131 "$patch_file"
	echo "----------"
	do_get_header "$patch_file"

	override=true
	commit patch
	override=false
}

git()
{
	if ! $override; then
		$orig_git "$@"
		return $?
	fi

	case "$1" in
	rev-parse)
		echo "$PWD"
		;;
	diff-files)
		;;
	cat-file)
		echo "committer 12345678 5"
		;;
	write-tree)
		# just one hash
		echo "f1d2d2f924e986ac86fdf7b36c94bcdf32beec15"
		;;
	commit-tree)
		exit 0
		;;
	update-ref)
		rm -f "$TMP_MSG"
		for arg in author_date_str author_str ct GIT_AUTHOR_DATE GIT_AUTHOR_EMAIL GIT_AUTHOR_NAME GIT_COMMITTER_DATE; do
			echo "$arg is \"$(eval "echo \$$arg")\""
		done
		override=false
		exit 0
		;;
	esac
}

_main()
{
check <<"EOF"
From: John Doe <john.doe@example.com>
Date: Thu, 15 Aug 2024 10:51:32 +0100
Subject: [PATCH] Pretty long subjects line
second

line 1
line 2
line 3


diff --git a/xyz b/xyz
index 34697ba58..0e2d8365b 100644
--- a/xyz
+++ b/xyz
EOF

check <<"EOF"
Subject message

line 1
line 2

line 3
 
diff --git a/abc b/abc
EOF

check <<"EOF"
From f572d396fae9206628714fb2ce00f72e94f2258f Mon Sep 17 00:00:00 2001
From: John Doe <john.doe@example.com>
Date: Wed, 7 Nov 2018 09:31:17 +0000
Commit-ID: ignore
Gitweb: ignore
AuthorDate: Wed, 8 Nov 2018 09:31:17 +0000
Committer: ignore
CommitDate: Wed, 9 Nov 2018 09:31:17 +0000
Subject: [PATCH] Pretty long subjects line
 second

line 1
EOF

rm -f "$patch_file"

echo "All tests passed!"
}
